### ISSUE TITLE
SetOf(type) and other collection checkers

### ISSUE THREAD

**Issue by callumlocke** [mako-taco/DecorateThis#12]
What about `SetOf(type)`, like `ArrayOf` but for ES6 sets?

Maybe also `MapOf(keyType, valueType)`?

This also got me thinking about extensibility... for example, if I am using an a custom/library-provided collection type like [`Immutable.OrderedSet`](http://facebook.github.io/immutable-js/), is there some way I could define my own `ImmutableOrderedSetOf(type)` (which I could then compose with other built-ins like `Optional` or `ArrayOf()`, etc)?

Maybe extensibility could be provided with a 'custom' type checker, which lets you supply a callback to examine the value in a custom way, like this:

``` js
import {Custom} from 'decorate-this';

const ImmutableOrderedSetOf = Custom((value, type) => {
  return value instanceof Immutable.OrderedSet && value.every(item => {
    return item instanceof type;
  });
});

@param(ImmutableOrderedSetOf(String))
function (strings) {
  // ...
}
```

(I don't actually know if this would work, just an idea.)

**Comment by mako-taco** [comment]
I do eventually want to support custom types.  For now, I will probably just add SetOf, MapOf.

I will think on the API for a custom type checker afterwards.  I could just expose `Validator` and `ValidatorResult` which I use internally, but they are a little confusing, and usually overkill for simple types.

**Comment by mako-taco** [comment]
I think this will get us by.

``` js
const ImmutableMap = KeyedCollection(Immutable.Map, map => map.toObject());
const ImmutableListOf = TypedCollection(Immutable.List, list => list.toArray());

class T {
    @param(ImmutableMap({key: String, val: String}))
    doThing() {
    }

    @param(ImmutableListOf(Number))
    doOtherThing() {
    }
}
```

`KeyedCollection` takes two arguments, a constructor/class and a transformation function. It returns a function which takes a type.
- The transformation function must return a plain Object

`TypedCollection` takes two arguments, a constructor/class and a transformation function. It returns a function which takes a type.
- The transformation function must return either an Array or an Object.
- The returned value will be iterated over with a `for...of` loop
- Each member of the value will be validated against the type

@callumlocke any comments?

**Comment by callumlocke** [comment]
looks great
