### ISSUE TITLE
@returns(Self) ?

### ISSUE THREAD

**Issue by callumlocke** [mako-taco/DecorateThis#14]
another idea (sorry :)... it could be useful to assert that a function implements a chaining API, i.e. that it returns whatever `this` context the function was called in, using something like `@returns(Self)`:

``` js
class Foo {
  constructor() {
    this.total = 0;
  }

  @param(Number)
  @returns(Self)
  add(number) {
    this.total += number;
    return this;
  }
}

new Foo().add(12).add(43).add(52);
```

Obviously it wouldn't make sense to use this with `@param` though. Maybe this would be more suitable as a new decorator, `@chainable()` or something.

**Comment by mako-taco** [comment]
what do you think of having the decorator handling the return (as opposed to just checking it)?

``` js
class T {
  @chainable
  add(number) {
    this.total += number;
  }
}
```

**Comment by callumlocke** [comment]
Interesting. I guess so, why not

**Comment by callumlocke** [comment]
Actually, I've been thinking about this, and here is an opinion... Having a decorator called `chainable` feels like a small piece of automation that doesn't actually add much value (it's just as easy and more explicit to `return this`). And it feels like it's straying from the 'type-checking' purpose of this library. In fact, I think you should consider refocusing the whole library so it's not just a "mixed bag" of decorators, and instead it's purely decorators for adding type-checking to JS. In other words, get rid of "debounce", "curry" etc. (or put them in a separate lib). And change the name to something like "type-decorators" or "strict-type". The library is already 90% about type-checking anyway, and I think it might have more appeal if it was completely focused on it. You may disagree though.

**Comment by callumlocke** [comment]
did you mean to close this?

**Comment by mako-taco** [comment]
yeah, wont be adding it

**Comment by callumlocke** [comment]
any particular reason? do you have another way for verifying that a method returns `this`?
