### ISSUE TITLE
Multi args @param validations

### ISSUE THREAD

**Issue by saggiyogesh** [mako-taco/DecorateThis#19]
How `@param` validations can be done in this way.

``` javascript
@param(Number, Number)
addToDimensions(x, y) {
    this.x += x;
    this.y += y;
}
```

Think it's more intuitive to understand. Currently its not supported.

**Comment by mako-taco** [comment]
I don't plan on adding this as a feature.  I believe there should only be one way to do everything, to keep code consistent.  Having multiple `@param` decorators for a single function lets you write these decorators as you would write JSDocs
