### ISSUE TITLE
Instance specific

### ISSUE THREAD

**Issue by megawac** [mako-taco/DecorateThis#3]
Cross posting an issue I ran into when implementing a similar project a couple months back (https://github.com/megawac/lodash-decorators)

Decorators are not instance level in current state, https://github.com/wycats/javascript-decorators/issues/13, meaning if you create multiple instances of a class you may be surprised. Example:

``` js
class X() {
   constructor(y) {
        this.x = y;
   }
   @memoize
   foo() {
     return this.x;
   }
}

console.log(x1.foo(1), x2.foo(1)) // What should x2 be
```

If you can think of a reasonable way to address that issue (I'm leaning towards `WeakMap`s myself, I'd be interested)

(This will apply to a number of other decorators such as `debounce`)

**Comment by mako-taco** [comment]
Thanks for bringing this to my attention.the context of functions need to be included in the map key, or a new map will need to be created for each instance

**Comment by mako-taco** [comment]
2d59a9b0add3bdc4fcd3eda5831ea9dd5e86e655 addresses this issue for `@memoize` (`@debounce` is still at large)
