### ISSUE TITLE
Type-checking for promise fulfillment values

### ISSUE THREAD

**Issue by callumlocke** [mako-taco/DecorateThis#8]
For ES7 async functions (or any other method that returns a promise), it would be nice to be able to type-check the fulfillment value of the promise (should it ever resolve).

The API could look like this:

``` js
class Foo {
  @returns(PromiseOf(Number))
  async someMethod() {
    await something();
    return 123;
  }
}
```

...although looking at the validator class, I'm not sure how that would work. Maybe a new decorator would be better, similar to `returns`:

``` js
class Foo {
  @promises(Number)
  async someMethod() {
    await something();
    return 123;
  }
}
```

Either way, I imagine it working like this:
1. the return value has to be a thenable, otherwise a TypeError will be thrown synchronously (i.e. same behaviour as `@returns({then: Function})`.)
2. the wrapper function returns a new promise which
   1. waits for the original promise to resolve,
   2. type-checks the fulfillment value of the original promise
      - if it fails the type check, reject the new promise
      - if it passes the type check, resolve the new promise with the fulfillment value

**Comment by mako-taco** [comment]
I like this API a lot. Should be easy to reuse the existing validator logic, just wrapped in a promise, as you suggest.  

I have two concerns:
1. I have to more-or-less do duck-typing to see if a value is a promise (since `Promise` is going to be my local copy of Babel's runtime Promise)
2. I cannot think of a clean way to create a wrapping promise that is _the same type of promise_ as the promise that is originally returned
3. I could return a new ES6 `Promise`, but that would leave people without most of the methods they gain from using custom promise libraries

What are your thoughts for solving this problem?

**Comment by callumlocke** [comment]
Yes, it's true you have to do duck typing, the short answer is don't worry about this, it's just a fact of life with promises :) Kyle Simpson covers it well [here](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20&%20performance/ch3.md#thenable-duck-typing).

About the other concern... I see what you mean, it would be confusing to return a different type of promise. But fortunately you don't need to do this, you can just chain a `.then(...)` on the end of the original promise, and do your type checking inside that. This effectively returns a new promise, but it will be of the exact same type.

Here is an example (not tested) for `@promises(type)`, based on your `@returns(type)` decorator:

``` js
export function promises(type, description) {
    return (target, name, descriptor) => {
        const value = descriptor.value || descriptor.initializer();
        descriptor.value = function promisesWrapper(...args) {
            const returnValue = value.apply(this, args);

            // first make sure it's a thenable
            if (!returnValue || typeof returnValue.then !== 'function') {
                throw new TypeError(
                    `${name} type mismatch: Expected a thenable`
                );
            }

            // then just return the promise, but with an extra step that rejects it
            // if it tries to resolve with the wrong type
            return returnValue.then(fulfillmentValue => {
                const result = Validator.validate('promised value', fulfillmentValue, type);

                if (result) {
                    // throwing from inside .then() effectively rejects the promise.
                    throw new TypeError(
                        `${name} type mismatch: ${result.getMessage()}`
                    );
                }

                return fulfillmentValue;
            });
        };

        return descriptor;
    };
}
```

I think `@promises(type)` is the best API for this, not `@returns(PromiseOf(type))`, for various reasons, but what do you think?

**Comment by mako-taco** [comment]
This looks good. Want to push a branch?
